# Generated by Django 4.0.4 on 2022-04-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
